title: Marc Mogdanz
theme:
  - PaperMod
baseURL: https://marcmogdanz.de
languageCode: en-us

enableRobotsTXT: true
paginate: 5
author:
  # used in RSS feeds
  name: Marc Mogdanz

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: archive
      name: Archive
      url: /archive
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact
      weight: 30
    - identifier: feed
      name: Feed
      url: /posts/index.xml
      weight: 40

params:
  #
  # PaperMod
  #

  # dark/light mode
  defaultTheme: auto

  homeInfoParams:
    Title: Hey, I'm Marc &#9995;
    Content: >
      - I'm a Backend Developer working for [Instant Commerce](https://instantcommerce.io) in Amsterdam &#127475;&#127473; on shaping the future of headless ecommerce &#9889;

      -

      - I love working with NestJS and Postgres for my backends and Next.js and Tailwind CSS for my frontends. My go-to hosting solutions consist of Vercel, supabase and Hetzner Cloud, or AWS and bare metal for demanding projects.

  socialIcons:
    - name: GitHub
      url: https://github.com/MarcMogdanz/
    - name: LinkedIn
      url: https://linkedin.com/in/marc-mogdanz/
