title: Marc Mogdanz
theme:
  - PaperMod
  - "plausible-hugo"
baseURL: https://marcmogdanz.de
languageCode: en-us

enableRobotsTXT: true
paginate: 5
author:
  # used in RSS feeds
  name: Marc Mogdanz

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact
      weight: 30
    - identifier: feed
      name: Feed
      url: /posts/index.xml
      weight: 40

params:
  #
  # PaperMod
  #

  # dark/light mode
  defaultTheme: auto

  homeInfoParams:
    Title: Hey, I'm Marc &#9995;
    Content: >
      - I'm working as a Backend Developer and Infrastructure Dude&trade; for [narando](https://about.narando.com).

      - Additionally I'm studying at [Bielefeld University of Applied Sciences](https://fh-bielefeld.de) for my Bachelor's degree in Business Informatics.

      -

      - I love working in JavaScript/TypeScript and Node.js with AWS, Hetzner Cloud and bare metal as my go-to hosting solutions.

  socialIcons:
    - name: GitHub
      url: https://github.com/MarcMogdanz/
    - name: GitLab
      url: https://gitlab.com/MarcMogdanz
    - name: LinkedIn
      url: https://linkedin.com/in/marc-mogdanz/

  #
  # Plausible
  #

  plausible:
    enable: true
    domain: marcmogdanz.de
    selfhosted_domain: plausible.marcmogdanz.de
    outbound_link: true
